config/routes.rb
Rails.application.routes.draw do
  
  
  get 'categories/culture'
  get 'categories/nature'
  get 'categories/science'
  get 'categories/mind_body'
  get 'categories/gov_jus'
  get 'categories/human'

  get 'notice/index'

  get   'settings/profile'
  patch 'settings/profile'  => 'settings#profile_update'
  get   'settings/email'  
  patch 'settings/email'    => "settings#email_update" 
  get   'settings/password'
  patch 'settings/password' => 'settings#password_update'
  
  
  get 'sessions/new'

  root 'articles#index'
  get  'static_pages/home'
  get  'static_pages/help'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  post '/tangos/search', to: 'tangos#search'
  post 'tango_lists/search', to: 'tango_lists#search'

  
  resources :users do
    resources :tango_lists, only: [:index]
    member do
      get :following, :followers
    end
  end
  
  resources :articles do
    get :autocomplete_tango_word, :on => :collection    
    resources :picks do
      resources :likes, only: [:create, :destroy]
    end
  end
  
  resources :relationships,  only: [:create, :destroy]
  resources :tangos do
    resources :tango_lists, only: [:create, :destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :notices, dependent: :destroy
  has_many :picks, dependent: :destroy
  default_scope -> { order(post_time: :desc) }
  scope :culture, ->{where(category: "Culture")}
  scope :nature,  ->{where(category: "Nature")}
  scope :science,  ->{where(category: "Science")}
  scope :mind_body,  ->{where(category: "Mind & Body")}
  scope :gov_jus,  ->{where(category: "Government & Justice")}
  scope :human,  ->{where(category: "Human")}

  mount_uploader :shudopic, ArticlePicUploader
  require 'csv'
  require 'open-uri'

  # article Article.new
  # article.get_target("サイト名")で全部取得できる。 sciame とか mnt とか
  
  #単語リストを配列にして吐き出す
  def self.get_tags
    tags = []
    csv_data = CSV.read(Rails.root.join('app', 'assets', 'csvs','wanteds.csv'))
    csv_data.each do |word|
      tags.push(word[0])
    end
    return tags.to_s
  end



  #検索機能。index のところで呼び出される。検索ワードがなければ全部の記事
  def self.search(search)
    search.strip! if search
    if search == ""
      Article.all              #空欄なら全部
    elsif search  
      # \" のおかげで "" で囲まれてる "dog" だけをひろい "hotdog" を拾わない
      Article.where(['tag LIKE ?',  "%\"#{search}\"%"])
    else
      Article.all
    end
  end

  
  #記事のカテゴリーを用意したカテゴリに合わせる
  def get_categories(target_category, site_name=ScientificAmerican)
    result = ""
    categories = []
    #csvファイルを開く。 category_sciame.csv にデータをいれてある。
    csv_data = CSV.read(Rails.root.join('app', 'assets', 'csvs', 'category', "category_#{site_name}.csv"))
  
    #csvのデータをハッシュにいれる
    csv_data.each do |word|
      categories.push(word)
    end
    
    #記事のカテゴリを自サイトのカテゴリに合わせる
    categories.each do |category|
      result =  category[1] if category[0] == target_category
    end
    return  result
  end

  
  #一覧ページのリンクを取得する。get_targetで呼び出される
  def get_links 
    target_links = []
  
    doc = Nokogiri::HTML(open(@idx_link))
    doc.xpath(@each_link).each do |link|
      target_links.push( @httpwww + link[:href].to_s) 
    end
    return target_links
  end  
  
  #csv から重要単語の配列を拾ってくる
  def get_wanteds
    wanteds = []
    csv_data = CSV.read(Rails.root.join('app', 'assets', 'csvs','wanteds.csv'))
    csv_data.each do |word|
      wanteds.push(word)
    end
    return wanteds
  end
  
  
  
  
  #txt から単語数をかぞえる
  def count_word(txt)
    return txt.downcase.gsub(/\(|\)|\.|\d+|\,|\!|\?|\"|“|”|\:|…|\s\-\s|\-{2,}/ , "").split(" ").length
  end  
  
  
  def hikaku(targets)
    #重要単語の配列を取得
    wanteds = get_wanteds
    #カウンター
    count = 0
    #抽出した単語を入れる配列
    daiji_words = {}
  
    #記事の単語と用意した単語を比較して daiji_words というハッシュにいれる
    targets.each do |target|
      wanteds.each do |wanted|
        if wanted[0] == target
          #daiji_words["vary"] = "～をかえる" => {"vary"=>"～をかえる"}
          daiji_words[wanted[0]] =  wanted[1]
        end
      end
    end
    return daiji_words
  end
  
  def get_target(site_name)
    urls    = []
    results = []
    counter = 0
    lem = Lemmatizer.new
    
    case site_name
      when "sciame"
        @idx_link  = "https://www.scientificamerican.com/section/lateststories/"
        @each_link = '//article/div/h2/a' 
        @httpwww   = ""
        
        @title     = "//main/header/div/h1"
        @preface   = "//main/header/div/p"
        @body      = '//main/div[2]/div[2]/div/section/div/div/div/p'
        @pic       = '//main/div[2]/div[2]/div/section/figure[1]/div//img'
        @category  =  '//header/div/div/a'
        @sitename  = "Scientific American"


      when "history"
        @idx_link  = "http://www.history.com/news"
        @each_link = "//body/div[2]/div/div/div/div[1]/div/div/strong/a"
        @httpwww   = "http://www.history.com"
        
        @title     = "//body/div[2]//div/h1[@class = 'title']"
        @preface   = "//article/p"
        @body      = "//article/div[2]/p"
        @pic       = '//body/div[2]//img'
        @category  = "Culture"
        @sitename  = "History"

        
      when "mnt"
        @idx_link  = "http://www.medicalnewstoday.com/"
        @each_link = "//body/div[3]/div/div[1]/div/div/ul/li/a"
        @httpwww   = "http://www.medicalnewstoday.com"
        
        @title     = "//article/div[1]/h1"
        @preface   = "//article/div[2]/div[5]/div/header"
        @body      = "//article/div[2]/div[5]/div"
        @sitename  = "Medical News Today"
        @pic       = "//article/div[2]/div[5]//div[@class='photobox_right']//img"
    end    
    
    
    # index ページからリンクを取得
    target_links = get_links
    target_links.each do |target_link|
      urls.push(target_link)
    end
  
    Anemone.crawl(urls, :depth_limit => 0, :delay=>1) do |anemone|
      anemone.skip_links_like /\/podcast\/|\/video\//
      anemone.on_every_page do |page|
        hash = Hash.new{|h,k| h[k]=[]}
        doc  = Nokogiri::HTML.parse(page.body)
        
        #サイトによってリンクが格納されてるセレクタが異なる。pic はhttps://www.natiogeo～.jpgみたいな形式に。
        if @sitename == "Medical News Today"
          pic = doc.at(@pic).attribute('data-src').to_s
        elsif doc.at(@pic)
          pic = doc.at(@pic).attribute('src').to_s
        end
        
        #カテゴリをつける。historyは強制culture
        if @sitename == "History"
          category = @category
        else
          target_category = doc.xpath(@category.to_s).text
          category = get_categories(target_category, @sitename.gsub(" ", ""))
        end
        
        #インスタンス変数は上の switch で取得  
        sitename = @sitename
        url   = urls[counter]
        title = doc.xpath(@title).text
        preface = doc.xpath(@preface).text
        body  = doc.xpath(@body).text
        word_count = count_word(body) 

        #1時間単位で適当に足すことでランダム投稿機能をつけてる
        post_time  = Time.zone.now + 60*60*(rand(10)+1)
        

        #######画像ダウンロード
        kakuchosi = File.basename(pic).match(/((\..*)(?=\?))|(\..*)/)
        day      = post_time.strftime("%Y%m%d%H%M")
        fileName = title.gsub(" ", "_").gsub(/\(|\)|\.|\d+|\,|\!|\?|\"|“|”|\r|\n|\:|…|\s\-\s|\-{2,}|\[|\]/ , "")         #picの名前を数字のハッシュに変えた
        dirName  = "app/assets/images/"      #asset/imagesに保存する
        filePath = dirName + day.to_s + "_" + fileName + kakuchosi.to_s 
        
        open(filePath, 'wb') do |output|     #保存するパス名。画像の名前まで書くと画像ファイルが作られる
          open(pic) do |data|                #保存したい画像のリンク
            output.write(data.read) 
          end
        end
        ######################        
        
        full_txt = (title + preface + body).downcase.gsub(/\(|\)|\.|\d+|\,|\!|\?|\"|“|”|\r|\n|\:|…|\s\-\s|\-{2,}/ , "")
                    .split(" ").uniq 
        full_txt.map! {|item| lem.lemma(item)}
      
        hash[:daiji_words] = hikaku(full_txt.uniq)
        hash[:title] = title
        hash[:body]  = preface.gsub(/\t|\n/, "")[0, 200]
        hash[:url]   = url
        hash[:pic]   =  day.to_s + "_" + fileName + kakuchosi.to_s 
        hash[:tag]   = hikaku(full_txt.uniq.sort).map{|k,v| k} #英単語の部分だけ
        hash[:site_name] = sitename
        hash[:count] = word_count
        hash[:category]  = category
        hash[:post_time] = post_time
      
        results.push(hash)
        counter += 1
        
        
      end
    end
  return results
  end


#  default_scope { where('post_time >= ?', Time.zone.now) }
=begin
  validates :daiji_words, presence: true
  validates :sitename,    presence: true,
                          length: {maximum:200, minimum: 1}
  validates :title, presence: true,
                    length: {maximum: 1000, minimum: 10}
  validates :body,  presence: true,
                    length: {maximum: 301, minimum: 10}
  #validates :count, presence: true,
  #                  length: {maximum: 2000, minimum: 30}
  validates :url,   uniqueness: true,
                    format: URI::regexp(%w(http https))
  validate  :picture_size

=end

  private
    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:shudopic, "should be less than 5MB")
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  autocomplete :tango, :word
  before_action :admin_user?, except: [:index, :show]

  

  def index
    @articles = Article.all.search(params[:search]) #.limit(10)
  end

  def show
    if logged_in?
      @pick = current_user.picks.find_by(article_id: @article.id) || Pick.new
    end
    @now  = Time.zone.now
    @new_articles = Article.order(created_at: :desc).limit(10)
    @past = @article.created_at 
    @dif_time = @past - @now
  end

  def new
    @article  = Article.new 
    @articles = Article.select(:category).distinct
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    title = params[:article][:title]
    body  = params[:article][:body]
    full_text = get_full_text(title.to_s, body.to_s)
    @article.daiji_words = hikaku(full_text)
    @article.body  = body.to_s.gsub(/\t|\n/, "")[0, 200]
    @article.tag   = hikaku(full_text.uniq.sort).map{|k,v| k}
    @article.count = count_word(body.to_s)
    @article.save
    redirect_to 'index'
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end
  

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title,:body, :site_name, :url, :shudopic, :category, :post_time)
    end


end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  ONE_DAY  = 86400
  ONE_HOUR = 3600
  
  # index で○○時間前と表示する
  def time_ago(past)
    now  = Time.zone.now
    dif_time = (now - past).to_i
    puts dif_time

    if dif_time < ONE_HOUR
      return ( (dif_time/60).to_s + "分前")
    elsif  ONE_HOUR <= dif_time && dif_time <= ONE_DAY
      return ((dif_time/60/60).to_s + "時間前")
    else 
      return past.year.to_s + "/" + past.month.to_s + "/" + past.day.to_s  
    end
  end
  
  #article用の画像。clockで取得したら:pic へ、手動でいれたら :shudoupic に入るからそのため。
  def image_tag_for_article(article)
    if !article.pic.nil?
      image_tag article.pic, size: "450x300"
    elsif !article.shudopic.nil?
      image_tag article.shudopic, class:"show-div"
    else
      image_tag 'default.jpg'
    end
  end

  #txt から単語数をかぞえる
  def count_word(txt)
    return txt.downcase.gsub(/\(|\)|\.|\d+|\,|\!|\?|\"|“|”|\:|…|\s\-\s|\-{2,}/ , "").split(" ").length
  end  


  #csv から重要単語の配列を拾ってくる
  def get_wanteds
    wanteds = []
    csv_data = CSV.read(Rails.root.join('app', 'assets', 'csvs','wanteds.csv'))
    csv_data.each do |word|
      wanteds.push(word)
    end
    return wanteds
  end
  
  def get_full_text(title, body)
    lem = Lemmatizer.new
    full_txt = (title + body).downcase.gsub(/\(|\)|\.|\d+|\,|\!|\?|\"|“|”|\r|\n|\:|…|\s\-\s|\-{2,}/ , "")
                .split(" ").uniq 
    full_txt.map! {|item| lem.lemma(item)}
  end
  
  
  def hikaku(targets)
    #重要単語の配列を取得
    wanteds = get_wanteds
    #カウンター
    count = 0
    #抽出した単語を入れる配列
    daiji_words = {}
  
    #記事の単語と用意した単語を比較して daiji_words というハッシュにいれる
    targets.each do |target|
      wanteds.each do |wanted|
        if wanted[0] == target
          #daiji_words["vary"] = "～をかえる" => {"vary"=>"～をかえる"}
          daiji_words[wanted[0]] =  wanted[1]
        end
      end
    end
    return daiji_words
  end

end

app/views/articles/_comment.html.erb
<div class="profile-wrapper">
  <%= link_to(user, class:"list-group-item") do %>
    <div class="user-profile">
      <h4 class="list-group-item-heading">
        <div class="name"><%= user.name %></div>
        <div class="user-pic"><%= image_tag user.user_pic, size: "30x30" %></div>
      </h4>
    </div>  
  <% end %>
  <p class="list-group-item-text" id="comment-<%= user.id %>">
    <%= simple_format(h(pick.comment)) %>
  </p>
</div>

app/views/articles/_like.html.erb
<%#
  #pick と article user(コメント主), pickが引数 
  #今のユーザーが like しててたらtrue
%>
<div class="like-panel">
  <% if pick.likes.find_by(user_id: current_user.id) %>
    <!--いいねとりけしボタン-->
    <div id="like-button-<%= user.id %>">
      <%= button_to article_pick_like_path(article.id, pick.id, Like.where(user_id: user.id, pick_id: pick.id)), method: :delete, class:"btn", params:{article_id: article.id, pick_user_id: user.id}, remote: true do %>
        <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
        <span><%= pick.likes.count %>いいね</span>
      <% end %>
    </div>  
  <% else %>
    <!--いいねボタン-->
    <div id="like-button-<%= user.id %>">
      <%= button_to article_pick_likes_path(article.id, pick.id), method: :post, class:"btn", params:{article_id: article.id, pick_user_id: user.id}, remote: true do %>
        <i class="fa fa-heart" aria-hidden="true"></i>
        <span><%= pick.likes.count %>いいね</span>
      <% end %>
    </div>  
  <% end %>
</div>

<!--article_pick_like_path(article.id, pick.id)

<%#= form_for (pick.likes)  id: "like-button like-#{user.id}", class:"btn", remote: true do %>

-->

app/views/articles/_newly_article.html.erb
<div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="../img/img1.png" alt="写真1">
      <div class="carousel-caption">
        <h1>写真1</h1>
          <p>おいしいコーヒーと自分だけの時間</p>
      </div>
    </div>
    <div class="item">
      <img src="../img/img2.png" alt="写真2">
      <div class="carousel-caption">
        <h1>写真2</h1>
      </div>
    </div>
    <div class="item">
      <img src="../img/img3.png" alt="写真3">
      <div class="carousel-caption">
        <h1>写真3</h1>
      </div>
    </div>
  </div>

app/views/articles/create.js.erb
$("#like-2").html("aaaaa");
$("#sample").html("現在じこく");

<%# $("#like-19").html("<i class="fa fa-heart" aria-hidden="true"></i><span><%= @pick_user.likes.count %></span>"); %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<link type="text/css" rel="stylesheet"
  href="http://code.jquery.com/ui/1.10.3/themes/cupertino/jquery-ui.min.css" />
<script type="text/javascript"
  src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript"
  src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript">
$(function() {
  // 2オートコンプリート機能を適用
  $('#txtKeywd').autocomplete({
    source: <%= sanitize Article.get_tags %>,
    autoFocus: true,
    delay: 100,
    minLength: 2
  });
});
</script>


<div class="col-sm-12" style="margin-bottom: 30px height: 200px;">
  <%= render 'carousel' %>
</div>
<br><br><br><br><br>

<div class="col-sm-12 col-offset-sm-2">
  <% unless @articles[0].nil? %>
    <% hajime_article = @articles[0] %>
    <div class="col-sm-12 thumbnail">
      <p><%= link_to image_tag(hajime_article.pic), hajime_article %></p>
      <div class="caption text-center">
        <h4><%= link_to hajime_article.title, hajime_article %></h4>
        <p><%= link_to hajime_article.site_name, hajime_article, class:"caption" %></p>
        <p><%= hajime_article.count %> words</p>
        <p><%= hajime_article.picks.count %> Picks</p>
        <p><%= time_ago hajime_article.post_time if hajime_article.post_time %></p>
      </div>
    </div>
  <% end %>
  <% unless @articles[1..8].nil?%>
    <% @articles[1..8].each do |article| %>
    <div class="col-sm-6 article" style="padding: 5px;">
      <span></span>
        <p class="pick"><%= article.picks.count %> Pick</p>
        <%= link_to image_tag(article.pic, class:"img-responsive"), article %>
        <div class="inner-article text-center">
          <h5><%= link_to article.title, article %></h5>
          <p><%= article.count %> words</p>
          <p><%= article.picks.count %> Picks</p>
          <p><%= time_ago article.post_time if article.post_time %></p>
        </div>
    </div>   
  <% end %>
  <% end %>
</div>


<% if false %>
<!--Culture 記事一覧-->
<div class="article-culture col-sm-12">
  <div>
    <h1 class="block-inline">Culture</h1>
    <span class="inline">
      <%= link_to content_tag(:i, "Culture 一覧をみる", class: "fa fa-chevron-right"), categories_culture_path %>
    </span>
  </div>  
  
  <% @articles.culture.limit(3).each do |article|%>
    <div class="col-sm-4">
      <div class="thumbnail">
        <p class="img-responsive"><%= link_to image_tag(article.pic), article %></p>
        <div class="caption text-center">
          <h4><%= link_to article.title, hajime_article %></h4>
          <p><%= link_to article.site_name, article, class:"caption" %></p>
          <p><%= article.count %> words</p>
          <p><%= article.picks.count %> Picks</p>
          <p><%= time_ago article.post_time if article.post_time %></p>
        </div>
      </div>      
    </div>  

  <% end %>
</div>

<!--Nature 記事一覧-->
<div class="article-nature col-sm-12">
  <div>
    <h1 class="block-inline">Nature</h1>
    <span class="inline">
      <%= link_to content_tag(:i, "Nature 一覧をみる", class: "fa fa-chevron-right"), categories_nature_path %>
    </span>
  </div>  
  <% @articles.nature.limit(3).each do |article|%>
    <div class="col-sm-4">
      <div class="thumbnail">
        <p class="img-responsive"><%= link_to image_tag(article.pic), article %></p>
        <div class="caption text-center">
          <h4><%= link_to article.title, hajime_article %></h4>
          <p><%= link_to article.site_name, article, class:"caption" %></p>
          <p><%= article.count %> words</p>
          <p><%= article.picks.count %> Picks</p>
          <p><%= time_ago article.post_time if article.post_time %></p>
        </div>
      </div>      
    </div>  
  <% end %>
</div>

<!--Science 記事一覧-->
<div class="article-science col-sm-12">
  <div>
    <h1 class="block-inline">Science</h1>
    <span class="inline">
      <%= link_to content_tag(:i, "Science 一覧をみる", class: "fa fa-chevron-right"), categories_science_path %>
    </span>
  </div>  
  <% @articles.science.limit(3).each do |article|%>
    <div class="col-sm-6">
      <div class="thumbnail">
        <p class="img-responsive"><%= link_to image_tag(article.pic), article %></p>
        <div class="caption text-center">
          <h4><%= link_to article.title, hajime_article %></h4>
          <p><%= link_to article.site_name, article, class:"caption" %></p>
          <p><%= article.count %> words</p>
          <p><%= article.picks.count %> Picks</p>
          <p><%= time_ago article.post_time if article.post_time %></p>
        </div>
      </div>      
    </div>  
  <% end %>
</div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>




<!--左サイドバー-->
<div class="col-sm-3 left-side" >
  <% if logged_in? %>
    <!--プロフィール-->
    <%= render 'shared/userstatus' %>
  <% end %>
    <!--重要単語を取得してハッシュにかえる-->
    <% clean_words = @article.daiji_words.gsub(/[{}"]/, "").gsub(/\=\>/, ":").delete(' ').split(/[:,]/) %>
    <% clean_words = clean_words.each_slice(2).map {|k, v| [k.to_sym, v] }.to_h %>
  
    <!--重要単語をテーブルで表示-->
    <% clean_words.each do |col, idx| %>
    <h3 style="background-color:#ADFF2F;"><%= col %></h3>
    <h5><%= idx %></h5>
  <% end %>
</div>

<!--メインコンテンツ-->
<div class="col-sm-6 show-div">
  <div class=" show-div">
    <!--トップ画像-->
    <%= image_tag_for_article(@article) %>
    <!--タイトル-->
    <p><%= link_to @article.title, @article.url, target: "_new", class: "show-div lead"%></p>
  
    <!--ソースと時間-->
    <span class="form-inline">
      <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
       <%= link_to @article.site_name, @article.site_name %>
      <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
      <%=  time_ago @article.post_time   %>
      <br>
    </span>
    <br><br><br>
    <!--本文の200文字-->
    <h4 class="show-div"> <%= @article.body %>....</h4>
    <br><br><br>
    
    <!--続きを読むボタン-->
    <div class="read-more col-sm-10  show-div">
      <%= link_to "続きを読む", @article.url, class: "read-more col-sm-10 show-div", rel: "noopener", target: "_blank" %>
    </div>
    
    <div id="here"></div>
    
    <br><br><br><br><br><br>
      
    <!--Pickボタン-->
    <% if logged_in? %>
      <div class="row pickc-n-omment">
        <% if @pick.user_id.nil? %>
          <%= form_for(@pick, url: article_picks_path(@article)) do |f| %>
            <%= f.text_area :comment, class: "col-sm-12 comment-area" %>
            <br>
            <%= f.submit "Pickする", class:"btn col-sm-offset-4 col-sm-4" %>
          <% end %>
        <!--unpickボタン-->  
        <% else %>
            <%= form_for(@pick, url: article_pick_path(@article, @pick), method: :patch) do |f| %>
            <%= f.text_area :comment, class: "col-sm-12 comment-area" %>
            <br>
            <%= f.submit "Pickする", class:"btn col-sm-offset-4 col-sm-4" %>
          <% end %>
          <%= link_to "UnPick", article_pick_path(@article, @pick), method: :delete, class:"col-sm-offset-1" %>
        <% end %>
      </div>
    <% end %>  
  </div>
  <div id="sample"></div>
  
  
    <br><br><br><br><br><br>
  
  <!--Pickしたユーザーとコメント-->
  <% if logged_in? %>
    <div class="col-sm-12 show-div">
      <div class="list-group">
        <div class="list-group-item my-pick">
            <strong>自分のコメント</strong>
            <% @article.picks.mypick(current_user).each do |pick| %>
              <%= render partial: 'comment', locals: {user: current_user, pick: pick} %>
            <% end %>
        </div>
    <br><br><br>
    
      <div class="list-group-item following-pick">
        <strong>フォロー中のコメント</strong>
        <% @article.picks.followpick(current_user).each do |pick| %>
          <% if(@user=User.find_by(id: pick.user_id)) #ここ代入してるよん%>
            <div class="user-<%=@user.id%>">
              <!--いいねフォーム-->
              <%= render partial: 'like', locals: {pick: pick, article: @article, user: @user} %>
              <!--コメント欄-->
              <%= render partial: 'comment', locals: {user: @user, pick: pick} %>
            </div>
          <% end %>
        <% end %>
      </div>

      <br><br><br>
      <div class="list-group-item other-pick">
        <strong>ほかのユーザーのコメント</strong>
        <% @article.picks.otherpick(current_user).each do |pick| %>
          <% if(@user=User.find_by(id: pick.user_id)) #ここ代入してるよん%>
            <div class="user-<%= @user.id %>">
              <!--いいねフォーム-->
              <%= render partial: 'like', locals: {pick: pick, article: @article, user: @user} %>
              <!--コメント欄-->
              <%= render partial: 'comment', locals: {user: @user, pick: pick} %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% else %>  
    <div class="col-sm-12 show-div">
      <div class="list-group">
        <div class="list-group-item my-pick">
            <strong>ほかの人のコメント</strong>
            <% @article.picks.all.each do |pick| %>
              <%= render partial: 'comment', locals: {user: User.find(pick.user_id), pick: pick} %>
            <% end %>
        </div>
      </div>
    </div>  
  <% end %>
  </div>
</div>

<div class="col-sm-3">
  <% @new_articles.each do |article|%>
    <div class="thumbnail article-<%=article.id%>" style="background-color:#D3D3D3; border: solid 3px white;">
      <p class="img-responsive"><%= link_to image_tag(article.pic), article  if article.pic != nil%></p>
      <p class="article-title"><%= link_to article.title, article %></p>
      <p class="article-sitename"><%= link_to article.site_name, article, class:"caption" %></p>
      <p class="article-count"><%= article.count %> words</p>
      <p class="article-pick-count"><%= article.picks.count %> Picks</p>
      <p class="article-timeago"><%= time_ago article.post_time if article.post_time %></p>
    </div>
  <% end %>
</div>