config/routes.rb
Rails.application.routes.draw do
  
  
  get 'categories/culture'
  get 'categories/nature'
  get 'categories/science'
  get 'categories/mind_body'
  get 'categories/gov_jus'
  get 'categories/human'

  get 'notice/index'

  get   'settings/profile'
  patch 'settings/profile'  => 'settings#profile_update'
  get   'settings/email'  
  patch 'settings/email'    => "settings#email_update" 
  get   'settings/password'
  patch 'settings/password' => 'settings#password_update'
  
  
  get 'sessions/new'

  root 'articles#index'
  get  'static_pages/home'
  get  'static_pages/help'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  post '/tangos/search', to: 'tangos#search'
  post 'tango_lists/search', to: 'tango_lists#search'

  
  resources :users do
    resources :tango_lists, only: [:index]
    member do
      get :following, :followers
    end
  end
  
  resources :articles do
    get :autocomplete_tango_word, :on => :collection    
    resources :picks do
      resources :likes, only: [:create, :destroy]
    end
  end
  
  resources :relationships,  only: [:create, :destroy]
  resources :tangos do
    resources :tango_lists, only: [:create, :destroy]
  end
end

app/models/tango_list.rb
class TangoList < ApplicationRecord
  belongs_to :tango
  belongs_to :user
  
  def self.search(search)
    if search.length == 1 
      Tango.where("initial = ?", search)
    elsif search == "all"
      Tango.all
    else
      Tango.all
      #Tango.where("initial = ?", "a")
    end
  end
  
end

app/controllers/tango_lists_controller.rb
class TangoListsController < ApplicationController
  before_action :set_user, only: [:index]
  before_action :logged_in_user?
  
  def search
    @tangos = current_user.my_lists.search(params[:q])
  end
  
  def create
    @tango_id = params[:tango_id]    #ajax でつかう
    current_user.tango_lists.create(tango_id: @tango_id)
  end


  def destroy
    @tango_list = current_user.tango_lists.find(params[:id])
    @tango_list.destroy
    @tango_id = params[:tango_id] #ajax で使う
  end

  def index
    @tangos = @user.my_lists
  end
  
  private
    def set_tango
      #@tango = Tango.find(params[:tango_id])
    end
    
    def set_user
      @user = User.find(params[:user_id]) || current_user
    end
end

app/helpers/tango_lists_helper.rb
module TangoListsHelper
end

app/views/tango_lists/_create_button.html.erb
<%= link_to '追加済', tango_tango_list_path(@tango_id, TangoList.find_by(tango_id: @tango_id)), method: :delete, remote: true %>

app/views/tango_lists/_destroy_button.html.erb
<%= link_to '単語帳に追加', tango_tango_lists_path(@tango_id), method: :post, remote: true %></td>

app/views/tango_lists/_search_result.html.erb
<table class="tango-list col-sm-8">
  <tbody>
    <% @tangos.each do |tango| %>
      <tr>
        <th><%= tango.word %></th>
        <td class="meaning col-sm-4"><%= tango.meaning %></td>
        <td class="button col-sm-4" id="list-button-<%= tango.id %>">
          <% if current_user.tango_lists.find_by(tango_id: tango.id) %>
            <%= link_to '追加済', tango_tango_list_path(tango.id, TangoList.find_by(tango_id: tango.id)), method: :delete, remote: true %>
          <% else %>
            <%= link_to '単語帳に追加', tango_tango_lists_path(tango.id), method: :post, remote: true%></td>
          <% end %>
        </td>  
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tango_lists/create.html.erb
<h1>TangoLists#create</h1>
<p>Find me in app/views/tango_lists/create.html.erb</p>

app/views/tango_lists/create.js.erb
$("#list-button-<%=@tango_id%>").html(
  "<%= escape_javascript(render('create_button')) %>");

app/views/tango_lists/destroy.html.erb
<h1>TangoLists#destroy</h1>
<p>Find me in app/views/tango_lists/destroy.html.erb</p>

app/views/tango_lists/destroy.js.erb
$("#list-button-<%=@tango_id%>").html(
  "<%= escape_javascript(render('destroy_button')) %>");

app/views/tango_lists/index.html.erb
<% alphabet = ["A","B","C","D","E","F","G","H","I","J","K","L","N","M","O","P","Q","R","S","T","U","V","W","X","Y","Z"] %>
<br><br><br><br><br><br>

<div class="row">
  <%= link_to "単語を登録する", tangos_path, class:"go-to-tangos" %>

  <div class="col-md-4">
    <ul class="list-inline">
      <%= link_to(content_tag(:li, "All", class: "alpha-btn red-btn"), tango_lists_search_path(q: "all"), class: "red-btn",method: :post ,remote: true )%>
      <% alphabet.each do |word| %>
        <%= link_to(content_tag(:li, word, class: "alpha-btn"), tango_lists_search_path(q: word.downcase),method: :post ,remote: true )%>
      <% end %>
    </ul>
  </div>

  <div class="col-md-8">
    <% if @tangos.empty? %>
      <h1>未登録のようです</h1>
    <% else %>
      <div id="lists">
        <table class="tango-list">
          <tbody>
            <% @tangos.each do |tango| %>
              <tr>
                <th class><%= tango.word %></th>
                <td><%= tango.meaning %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>  
    <% end %>
  </div>  

app/views/tango_lists/search.js.erb
$("#lists").html("<%= escape_javascript(render('search_result')) %>");