config/routes.rb
Rails.application.routes.draw do
  
  
  get 'categories/culture'
  get 'categories/nature'
  get 'categories/science'
  get 'categories/mind_body'
  get 'categories/gov_jus'
  get 'categories/human'

  get 'notice/index'

  get   'settings/profile'
  patch 'settings/profile'  => 'settings#profile_update'
  get   'settings/email'  
  patch 'settings/email'    => "settings#email_update" 
  get   'settings/password'
  patch 'settings/password' => 'settings#password_update'
  
  
  get 'sessions/new'

  root 'articles#index'
  get  'static_pages/home'
  get  'static_pages/help'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  post '/tangos/search', to: 'tangos#search'
  post 'tango_lists/search', to: 'tango_lists#search'

  
  resources :users do
    resources :tango_lists, only: [:index]
    member do
      get :following, :followers
    end
  end
  
  resources :articles do
    get :autocomplete_tango_word, :on => :collection    
    resources :picks do
      resources :likes, only: [:create, :destroy]
    end
  end
  
  resources :relationships,  only: [:create, :destroy]
  resources :tangos do
    resources :tango_lists, only: [:create, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_status.html.erb
<%# @user = || current_user%>
<div class="status">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
      following
    </strong>
  </a>
  <a href="<%=followers_user_path(@user)%>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
      followers
    </strong>
  </a>
</div>

app/views/shared/_userstatus.html.erb
<!--current_user の名前と写真とフォロワ数-->
<div class="userstatus">
  <div class="image-n-name">
    <%= link_to image_tag(current_user.user_pic, size: "100x100", class:"img-circle"), current_user %>
    <p><%= link_to(current_user.name, current_user, class:"text-center") %></p>
  </div>
  <div class="status">
    <a href="<%= following_user_path(current_user) %>">
      <strong id="following" class="stat">
        <%= current_user.following.count %>following
      </strong>
    </a>
    <a href="<%=followers_user_path(current_user)%>">
      <strong id="followers" class="stat">
        <%= current_user.followers.count %>followers
      </strong>
    </a>
  </div>
</div>