config/routes.rb
Rails.application.routes.draw do
  
  
  get 'categories/culture'
  get 'categories/nature'
  get 'categories/science'
  get 'categories/mind_body'
  get 'categories/gov_jus'
  get 'categories/human'

  get 'notice/index'

  get   'settings/profile'
  patch 'settings/profile'  => 'settings#profile_update'
  get   'settings/email'  
  patch 'settings/email'    => "settings#email_update" 
  get   'settings/password'
  patch 'settings/password' => 'settings#password_update'
  
  
  get 'sessions/new'

  root 'articles#index'
  get  'static_pages/home'
  get  'static_pages/help'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  post '/tangos/search', to: 'tangos#search'
  post 'tango_lists/search', to: 'tango_lists#search'

  
  resources :users do
    resources :tango_lists, only: [:index]
    member do
      get :following, :followers
    end
  end
  
  resources :articles do
    get :autocomplete_tango_word, :on => :collection    
    resources :picks do
      resources :likes, only: [:create, :destroy]
    end
  end
  
  resources :relationships,  only: [:create, :destroy]
  resources :tangos do
    resources :tango_lists, only: [:create, :destroy]
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_user
  before_action :logged_in_user?
  
  
  def profile
  end
  
  def profile_update
    respond_to do |format|

      if current_user.update_attributes(profile_params)
        format.html do
          redirect_to '/settings/profile'
          flash[:notice] = "更新できました"
        end
        format.js
      else
        format.html do 
          render 'settings/profile'
          flash[:danger] = "保存できませんでした。入力内容を確認してください"
        end
        format.js
      end   
    end
  end

  def email
    @email ||= current_user.email 
  end
  
  def email_update
    if current_user.update(email_params)
      redirect_to '/settings/email'
      flash[:notice] = "更新できました"
    else
      @email = current_user.attribute_was(:email)  
      render '/settings/email'
    end    
  end
  

  def password
  end
  
  def password_update
    if current_user.update(password_params)
      redirect_to '/settings/password'
      flash[:notice] = "更新できました"
    else
      render '/settings/password'
      flash[:danger] = "保存できませんでした。入力内容を確認してください" 
    end        
  end
  
  private
    
    def set_user
      @user = current_user
    end
  
    def email_params
      params.require(:user).permit(:email)
    end
    
    def profile_params
      params.require(:user).permit(:name, :hitokoto, :user_pic)
    end
    
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_left_sidebar.html.erb
<ul class="col-sm-3 list-group" style="list-style:none;">
  <li><%= link_to "プロフィール設定", settings_profile_path, class: "list-group-item" %></li>
  <li><%= link_to "メール設定", settings_email_path, class: "list-group-item" %></li>
  <li><%= link_to "パスワード設定", settings_password_path, class: "list-group-item" %></li>
</ul>

app/views/settings/email.html.erb
<% provide(:setting, "メールアドレスの設定") %>

<div class="col-sm-7">
  <%= render 'shared/error_messages' %>
  <div class="form-group row">
    <label class="col-sm-4 col-form-label">現在のメールアドレス</label>
    <div class="col-sm-8">
      <input type="text" class="form-control" placeholder="<%= @email %>" readonly>
    </div>
  </div>
  

  <div class="form-group row">
    <%= form_for(@user, url: settings_email_path, method: :patch) do |f| %>
            <label for="lgFormGroupInput" class="col-sm-4 col-form-label col-form-label-lg">新しいメールアドレス</label>
      <div class="col-sm-8">
        <%= f.email_field :email, class:"form-control form-control-lg", id: "lgFormGroupInput", value: ""  %>        
      </div>
      <br><br><br>
      <button type='submit' class="btn btn-primary btn-lg col-sm-offset-4 col-sm-4" >更新する</button>
    <% end %>
  </div>  
</div>

app/views/settings/password.html.erb
<% provide(:setting, "パスワードの設定") %>

<div class="col-sm-7">
  <div class="form-group row">
    <%= form_for(current_user, url: settings_password_path, method: :patch) do |f| %>

      <%= render 'shared/error_messages' %>
      <label for="lgFormGroupInput" class="col-sm-4 col-form-label col-form-label-lg">パスワード</label>
      <div class="col-sm-8">
        <%= f.password_field :password, class:"form-control form-control-lg", id: "lgFormGroupInput"  %>        
      </div>
      <br><br><br>

      <label for="lgFormGroupInput" class="col-sm-4 col-form-label col-form-label-lg">パスワードの確認</label>
      <div class="col-sm-8">
        <%= f.password_field :password_confirmation, class:"form-control form-control-lg", id: "lgFormGroupInput"  %>        
      </div>
      <br><br><br>

      <button type='submit' class="btn btn-primary btn-lg col-sm-offset-4 col-sm-4" >更新する</button>
    <% end %>
  </div>  
</div>

app/views/settings/profile.html.erb
<% provide(:setting, "プロフィールの設定") %>


<div class="col-sm-7">
  <div class="form-group row">
    <%= form_for(current_user, url: settings_profile_path, method: :patch) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <label class="col-sm-4 col-form-label col-form-label-lg">名前</label>
      <div class="col-sm-8">
        <%= f.text_field :name, class:"form-control form-control-lg" %>        
      </div>
      <br><br><br>
      
      
      <label class="col-sm-4 col-form-label col-form-label-lg">ひとこと</label>
      <div class="col-sm-8">
        <%= f.text_field :hitokoto, class:"form-control form-control-lg" %>
      </div>
      <br><br><br>
      
      <label class="col-sm-4 col-form-label">アイコン画像</label>
      <span class="col-sm-8">
        <%= f.file_field :user_pic, id:"file", style:"display:none;" ,accept: 'image/jpeg,image/gif,image/png'%>
        <input type="button" value="ファイル選択" class="btn btn-normal" onClick="$('#file').click();">
        <span id="img-profile">
          <%= image_tag(current_user.user_pic, size:"60x60", class:"img-circle", id: "preview") %>
        </span>
      </span>
      <br><br><br>
      
      <button type='submit' class="btn btn-primary btn-lg col-sm-offset-4 col-sm-4" >更新する</button>
      
    <% end %>
  </div>  
</div>

<script>
/*アップロード前にプレビュー表示*/
$('#file').change(
    function() {
        if ( !this.files.length ) {
            return;
        }
 
        var file = $(this).prop('files')[0];
        var fr = new FileReader();
        fr.onload = function() {
            $('#preview').attr('src', fr.result ).css('display','inline');
        }
        fr.readAsDataURL(file);
    }
);
</script>